/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FShowMessages.java
 *
 * Created on 23.06.2010, 20:44:30
 */

package geotweet;

import java.util.Collection;
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.ImageIcon;



/**
 *
 * @author R. C. Ladiges
 */
public class FShowMessages extends javax.swing.JFrame {
    protected GeotweetMessage message = null;
    protected LinkedList<GeotweetMessage> messages;
    protected FMainKarte mainframe;
    protected ListIterator<GeotweetMessage> msgit;
    protected boolean nexted = false;
    protected boolean preved = false;

    /** Creates new form FShowMessages */
    public FShowMessages(FMainKarte frame, Collection<GeotweetMessage> msgs) {
        this.messages = (LinkedList<GeotweetMessage>) msgs;
        this.msgit = this.messages.listIterator(0);
        this.mainframe = frame;
        initComponents();
        nextMessage();
    }

    protected void nextMessage(){
        if(msgit.hasNext()) this.message = msgit.next();
        if(preved && msgit.hasNext()) this.message = msgit.next();
        String title = "GeoTweet " + msgit.nextIndex() + " von " + messages.size();
        this.setTitle(title);
        nexted = true;
        preved = false;
        showMessage();
    }

    protected void prevMessage(){
        if(msgit.hasPrevious()) this.message = msgit.previous();
        if(nexted && msgit.hasPrevious()) this.message = msgit.previous();
        String title = "GeoTweet " + (msgit.previousIndex()+2) + " von " + messages.size();
        this.setTitle(title);
        preved = true;
        nexted = false;
        showMessage();
    }

    protected void showMessage(){
        jLabel1.setText(message.getDateTime());
        ImageIcon icon = message.getUser().getAvatarImageIcon();
        if(icon != null) jLabel2.setIcon(icon);
        else jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geotweet/default.png")));
        jLabel2.setToolTipText(message.getUsername());
        jLabel3.setText(message.getText());
        jButton2.setEnabled((!preved && msgit.hasNext()) || (preved && (msgit.nextIndex() < messages.size()+1)));
        jButton3.setEnabled((!nexted && msgit.hasPrevious()) || (nexted && (msgit.previousIndex() > 0)) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(435, 94));

        jLabel1.setText("time");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geotweet/default.png"))); // NOI18N

        jLabel3.setText("msg");

        jButton1.setText("reply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("prev");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jLabel3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainframe.newMessage(message.position.getY(), message.position.getX());
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        nextMessage();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        prevMessage();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                //new FShowMessages().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables





}
